"""Sua model payment

Revision ID: 11f71bced47c
Revises: a3cf434d44a8
Create Date: 2026-05-09 16:57:57.248030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11f71bced47c'
down_revision = 'a3cf434d44a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gateway_response', sa.Text(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=mysql.ENUM('CASH', 'MOMO', 'VNPAY', collation='utf8mb4_unicode_ci'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('method',
               existing_type=mysql.ENUM('CASH', 'MOMO', 'VNPAY', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
