"""update ticket db

Revision ID: 45adc8ec21e9
Revises: 4fe9a94e65cc
Create Date: 2026-05-09 17:46:00.742765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45adc8ec21e9'
down_revision = '4fe9a94e65cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['qr_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
