"""Update  model payment

Revision ID: 579eb948c842
Revises: 11f71bced47c
Create Date: 2026-05-09 17:26:16.596545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579eb948c842'
down_revision = '11f71bced47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_order_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('gateway_transaction_id')
        batch_op.drop_column('gateway_order_id')

    # ### end Alembic commands ###
