"""init tables

Revision ID: 835170005641
Revises: 
Create Date: 2026-04-29 12:46:25.928164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835170005641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ORGANIZER', 'USER', name='roleenum'), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='eventstatus'), nullable=True),
    sa.Column('image_poster', sa.String(length=255), nullable=True),
    sa.Column('image_banner', sa.String(length=255), nullable=True),
    sa.Column('organizer_brand', sa.String(length=100), nullable=True),
    sa.Column('organizer_logo', sa.String(length=255), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', sa.Enum('CASH', 'MOMO', 'VNPAY', name='paymentmethod'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showing_id', sa.Integer(), nullable=True),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['showing_id'], ['showings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showing_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('sold_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showing_id'], ['showings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=100), nullable=True),
    sa.Column('showing_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOCKED', 'SOLD', name='ticketstatus'), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['showing_id'], ['showings.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_id', name='uq_ticket_seat'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', name='uq_ticket_orderitem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('tickets')
    op.drop_table('ticket_types')
    op.drop_table('seats')
    op.drop_table('showings')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
