"""sửa model event

Revision ID: a7588f36e296
Revises: 809346e51b6d
Create Date: 2026-04-24 17:37:59.433578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7588f36e296'
down_revision = '809346e51b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_poster', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_banner', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('organizer_brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('organizer_logo', sa.String(length=255), nullable=True))
        batch_op.alter_column('event_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.alter_column('event_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
        batch_op.drop_column('organizer_logo')
        batch_op.drop_column('organizer_brand')
        batch_op.drop_column('image_banner')
        batch_op.drop_column('image_poster')
        batch_op.drop_column('city')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
